CREATE TABLE company (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE person (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    company_id INTEGER REFERENCES company(id) ON DELETE CASCADE
);

INSERT INTO company (name) VALUES
('Компания А'),
('Компания Б'),
('Компания В');

INSERT INTO person (name, company_id) VALUES
('Иван Иванов', 1),
('Мария Петрова', 2),
('Алексей Смирнов', 1),
('Ольга Сидорова', 3),
('Петр Васильев', NULL),
('Светлана Кузнецова', 2);

SELECT p.name, c.name AS company
FROM person p
LEFT JOIN company c ON p.company_id = c.id
WHERE p.company_id != 5 OR p.company_id IS NULL;

SELECT c.name AS company_name, COUNT(p.id) AS employee_count
FROM company c
JOIN person p ON p.company_id = c.id
GROUP BY c.name
HAVING COUNT(p.id) = (
    SELECT MAX(employee_count)
    FROM (
        SELECT COUNT(*) AS employee_count
        FROM person
        GROUP BY company_id
    )
);